### ISSUE TITLE
I'm doing it wrong ...

### ISSUE THREAD

**Issue by kingozorg** [Simbiat/HTMLCut#1]
Hi! Sorry - no real issue. 
I'm just not able to get your class to run. 
It is exactly what I am looking for, but I always get the error messages: 
Call to undefined function Cut() or "HTMLCut"  - What am I doing wrong? 

require_once 'HTMLCut.php';
$html = new HTMLCut($source_file);

Can you help? 
Cheers!

**Comment by Simbiat** [comment]
Firstly, you need to use `\Simbiat` namespace to create the object. Then you need to pass the string or DOM object to `Cut()` function, not to the constructor.
I've updated the readme with a proper example. I also adjusted the code itself a bit, so I would recommend downloading the newer version.

**Comment by kingozorg** [comment]
Thanks for the quick reply and the nice simple example. Now it works - the inclusion of classes is always difficult for me!
